### ISSUE TITLE
Win10  error

### ISSUE THREAD

**Issue by frankjoke** [sandeepmistry/node-bluetooth-hci-socket#108]
I (and all others) get errors on windows (Node 10.15.1 LTE) on my HP-notebook.

`

host.x360Frank | 2019-02-19 19:52:33.344 | error | instance system.adapter.radar2.0 terminated with code 0 (OK)
-- | -- | -- | --
host.x360Frank | 2019-02-19 19:52:33.344 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:61:11) errno: -12 }
host.x360Frank | 2019-02-19 19:52:33.344 | error | Caught by controller[0]: at Noble.<anonymous> (C:\iobroker\node_modules\iobroker.radar2\node_modules\@abandonware\noble\lib\noble.js:57:24)
host.x360Frank | 2019-02-19 19:52:33.344 | error | Caught by controller[0]: at NobleBindings.init (C:\iobroker\node_modules\iobroker.radar2\node_modules\@abandonware\noble\lib\hci-socket\bindings.js:82:13)
host.x360Frank | 2019-02-19 19:52:33.344 | error | Caught by controller[0]: at Hci.init (C:\iobroker\node_modules\iobroker.radar2\node_modules\@abandonware\noble\lib\hci-socket\hci.js:101:35)
host.x360Frank | 2019-02-19 19:52:33.344 | error | Caught by controller[0]: at BluetoothHciSocket.bindRaw (C:\iobroker\node_modules\iobroker.radar2\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:43:8)
host.x360Frank | 2019-02-19 19:52:33.344 | error | Caught by controller[0]: at BluetoothHciSocket.bindUser (C:\iobroker\node_modules\iobroker.radar2\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:90:19)
host.x360Frank | 2019-02-19 19:52:33.344 | error | Caught by controller[0]: at Device.usb.Device.open (C:\iobroker\node_modules\iobroker.radar2\node_modules\usb\usb.js:38:7)
host.x360Frank | 2019-02-19 19:52:33.344 | error | Caught by controller[0]: { Error: LIBUSB_ERROR_NOT_SUPPORTED

`

**Comment by bierzorutas** [comment]
+1 to LIBUSB_ERROR_NOT_SUPPORTED error
