### ISSUE TITLE
Failed Install - Win 10

### ISSUE THREAD

**Issue by 400HPMustang** [sandeepmistry/node-bluetooth-hci-socket#117]
OS: Windows 10
Node Version: 12.13.1

Trying to install on Windows 10, getting the error logged below
```
226 warn enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
227 verbose enoent This is related to npm not being able to find a file.
228 warn system32 No description
229 warn system32 No repository field.
230 warn system32 No README data
231 warn system32 No license field.
232 warn optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules\xpc-connection):
233 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
234 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
234 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
234 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
234 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
235 verbose stack Error: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
235 verbose stack Exit status 1
235 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
235 verbose stack     at EventEmitter.emit (events.js:210:5)
235 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
235 verbose stack     at ChildProcess.emit (events.js:210:5)
235 verbose stack     at maybeClose (internal/child_process.js:1021:16)
235 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
236 verbose pkgid bluetooth-hci-socket@0.5.1
237 verbose cwd C:\WINDOWS\system32
238 verbose Windows_NT 10.0.18362
239 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bluetooth-hci-socket"
240 verbose node v12.13.1
241 verbose npm  v6.12.1
242 error code ELIFECYCLE
243 error errno 1
244 error bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
244 error Exit status 1
245 error Failed at the bluetooth-hci-socket@0.5.1 install script.
245 error This is probably not a problem with npm. There is likely additional logging output above.
246 verbose exit [ 1, true ]
```

**Comment by 400HPMustang** [comment]
Fixed the install issue.
