### ISSUE TITLE
Error: No compatible USB Bluetooth 4.0 device found!

### ISSUE THREAD

**Issue by 400HPMustang** [sandeepmistry/node-bluetooth-hci-socket#118]
OS: Windows 10
Node: 12.13.1

I have three devices from your list of compatible devices, and I get the same error with either devices. I've tried removing, reinstalling, changing drivers, rebooting the machine, etc. No joy. 

If you could please offer some suggestions, that would be awesome. Thank you.

CSR8510 A10 | 0x0a12 | 0x0001
Asus BT-400 | 0x0b05 | 0x17cb
Intel Wireless Bluetooth 8265 | 0x8087 | 0x0a2b
```
Error: No compatible USB Bluetooth 4.0 device found!
    at BluetoothHciSocket.bindUser (C:\Users\Admin\AppData\Roaming\npm\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:87:11)
    at BluetoothHciSocket.bindRaw (C:\Users\Admin\AppData\Roaming\npm\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:43:8)
    at Hci.init (C:\Users\Admin\AppData\Roaming\npm\node_modules\@abandonware\noble\lib\hci-socket\hci.js:101:35)
    at NobleBindings.init (C:\Users\Admin\AppData\Roaming\npm\node_modules\@abandonware\noble\lib\hci-socket\bindings.js:82:13)
    at Noble.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\@abandonware\noble\lib\noble.js:57:24)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)[39m[22m
```

**Comment by zeespogeira** [comment]
edit the file `\bluetooth-hci-socket\lib\usb.js.` then I added usb.findByIds(0x8087, 0x0A2B) on line 66. The parameters were fetched from zadig.exe
![image](https://user-images.githubusercontent.com/3593156/77940188-378cb400-72b0-11ea-9632-e055a5de8ff9.png)
